Members/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('', views.index, name='users-index'),
    path('add-profile', views.ProfileCreateView.as_view(), name='add-profile'),
    path('<int:pk>/update-profile', views.ProfileUpdateView.as_view(), name='update-profile'),
    path('<int:pk>/delete-profile', views.ProfileDeleteView.as_view(), name='delete-profile'),
]

users/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    fname = models.CharField(max_length=20)
    sname = models.CharField(max_length=20)
    cover = models.FileField()
    bio = models.CharField(max_length=50)
    area_raised = models.CharField(max_length=50)
    primary_sch = models.CharField(max_length=50)
    high_sch = models.CharField(max_length=50)
    campus = models.CharField(max_length=50, blank=True)
    course = models.CharField(max_length=50, blank=True)
    hobby = models.CharField(max_length=50)
    year_joined_library = models.CharField(max_length=4)
    profession = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.fname

    def get_absolute_url(self):
        return reverse('users:users-index')

users/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = [
            'username', 'email', 'password'
        ]

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import CreateView, UpdateView, DeleteView
from .models import Profile
from django.db.models import Q
from .forms import UserForm
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


# Create your views here.
def index(request):
    profiles = Profile.objects.all()
    query = request.GET.get("q")
    if query:
        profiles = profiles.filter(
            Q(fname__icontains=query) |
            Q(sname__icontains=query)
        ).distinct()
        return render(request, 'users/index.html', {
            'profiles': profiles,
        })
    return render(request, 'users/index.html', {'profiles': profiles})


class ProfileCreateView(LoginRequiredMixin, CreateView):
    model = Profile
    fields = [
        'fname', 'sname', 'cover', 'area_raised', 'bio',
        'primary_sch', 'high_sch', 'campus', 'course',
        'hobby', 'year_joined_library', 'profession'
    ]

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ProfileUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Profile
    fields = [
        'fname', 'sname', 'area_raised', 'cover', 'bio',
        'primary_sch', 'high_sch', 'campus', 'course',
        'hobby', 'year_joined_library', 'profession'
    ]

    def test_func(self):
        profile = self.get_object()
        if self.request.user == profile.user:
            return True
        return False


class ProfileDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Profile
    success_url = '/'

    def test_func(self):
        profile = self.get_object()
        if self.request.user == profile.user:
            return True
        return False


def signup(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = form.save(commit=False)
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('users:users-index')
    return render(request, 'registration/signup.html', {'form': form})

users/templates/users/base.html
<html lang="en">
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
<link href='https://fonts.googleapis.com/css?family=Cabin Sketch' rel='stylesheet'>
<link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet'>
<link href='https://fonts.googleapis.com/css?family=Sofia' rel='stylesheet'>
<link href='https://fonts.googleapis.com/css?family=Bree Serif' rel='stylesheet'>
<link href='https://fonts.googleapis.com/css?family=Acme' rel='stylesheet'>
{% load static %}

<link href="{% static 'users/css/styles.css' %}" rel="stylesheet" type="text/css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="{% url 'users:users-index' %}" style="font-family: 'Acme', cursive;">BDADG ALUMNI PROFILES</a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
    <li class="nav-item">
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q" value="{{ request.GET.q }}">
      <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
    </form>
        </li>
    </ul>
    <ul class="navbar-nav">
        <li class="nav-item active">
            {% if user.is_authenticated %}
      <a class="nav-link" href="{% url 'users:add-profile' %}" style="font-family: 'Orbirton', cursive;"><i class="fas fa-user-plus" style="color: steelblue;"></i> Add Profile<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
      <a class="nav-link" href="{% url 'users:logout' %}" style="font-family: 'Orbirton', cursive;"><i class="fas fa-sign-out-alt" style="color: red;"></i> Logout<span class="sr-only">(current)</span></a>
      </li>
                {% else %}
                <li class="nav-item active">
      <a class="nav-link" href="{% url 'users:login' %}" style="font-family: 'Orbirton', cursive;"><i class="fas fa-sign-in-alt" style="color: red;"></i> Login<span class="sr-only">(current)</span></a>
      </li>
        {% endif %}
    </ul>
  </div>
</nav>
<div class="container">
    <h3 class="text-center my-2" style="font-family: 'Bree Serif', cursive;">"<b>I AM</b>  Because <b>WE ARE!</b>"</h3>
<hr>
    {% block content %}

    {% endblock %}


</div>



</body>
</html>

users/templates/users/index.html
{% extends 'users/base.html' %}
{% block title %}BDADG{% endblock %}

{% block content %}
<div class="row">
    {% if profiles %}
        {% for prof in profiles %}
            <div class="col-sm-3">
            <div class="card card-body my-1">
                <h3 style="color: black;text-align: center; font-family: Pacifico">{{ prof.fname }}&nbsp;{{ prof.sname }}</h3>
            <img src="{{ prof.cover.url }}" class="rounded-circle" alt="" style="height: 130px; width: 130px; align-self: center;">
                <div class="caption">
                    <h5 class="text-center" style="font-family: 'Droid Sans';">{{ prof.profession }}</h5>
                    <h6 class="text-center" style="font-family: FreeSerif;">{{ prof.bio }}</h6>
                    <a href="{% if prof.user == request.user %}{% url 'users:delete-profile' prof.id %}{% else %}{% endif %}" class="btn btn-danger btn-sm" style="float: right;"><i class="fas fa-trash"></i> </a>

                    <!-- Trigger the modal with a button -->
                    <button class="btn btn-info btn-sm" data-toggle="modal" data-target="#modal-{{ prof.id }}"><i class="fas fa-info"></i> </button>


                    <!-- Modal -->
                    <div class="modal fade" id="modal-{{ prof.id }}" role="dialog">
                        <div class="modal-dialog">

                            <!-- Modal content-->
                            <div class="modal-content">
                                <div class="modal-header" style="padding:5px 5px;">
                                    <h4 class="text-center" style="color: darkslategrey; font-family: 'Fira Code';"><b>{{ prof.fname }}&nbsp;{{ prof.sname }}</b></h4>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                </div>
                                <div class="modal-body">
                                    <p style="font-family: FreeSerif;">{{ prof.fname }} grew up in {{ prof.area_raised }}.
                                    Went to {{ prof.primary_sch }} Primary School. Then proceeded to {{ prof.high_sch }} High School..
                                    {% if prof.campus %}and later joined {{ prof.campus }} to pursue {{ prof.course }}.{% endif %} {{ prof.fname }} joined MYSA Mathare North Library in
                                    {{ prof.year_joined_library }} and participated in the Drama Group Activities. {{ prof.fname }} is a {{ prof.profession }}
                                     and likes {{ prof.hobby }}.</p>
                                </div>
                                <div class="modal-footer">
                                    <a href="{% if prof.user == request.user %}{% url 'users:update-profile' prof.id %}{% else %}{% endif %}" class="btn btn-success btn-sm" style="float: left;margin-right: 85%;"><i class="fas fa-edit"></i> </a>
                                     <a href="" class="btn btn-warning btn-sm" style="float: right;" data-dismiss="modal" ><i class="fas fa-times-circle"></i> </a>
                                </div>

                            </div>

                        </div>
                    </div>


                </div>
            </div>



            </div>
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

users/templates/users/profile_confirm_delete.html
{% extends 'users/base.html' %}

{% block title %}Delete {{ object.fname }}{% endblock %}
{% block content %}
    <div class="container">
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
            <div class="card card-body my-2">
                <h3 class="text-primary" style="font-family: 'Droid Serif';">Delete {{ object.fname }}</h3>
                <hr>
                    <form method="POST">
                        {% csrf_token %}
                        <fieldset class="form-group">
                            <h4 style="font-family: 'DejaVu Serif';">Are you want to Delete "Profile"&nbsp;?</h4>
                        </fieldset>
                        <div class="form-group">
                            <button type="submit" class="btn btn-outline-danger">Yes, Delete</button>
                            <a class="btn btn-outline-secondary" href="{% url 'users:users-index' %}">Cancel</a>
                        </div>
                    </form>

            </div>
        </div>
    </div>
    </div>
{% endblock %}

users/templates/users/profile_form.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block title %}{% if object %}Update&nbsp;{{ object.fname }}{% else %}Add Profile{% endif %}{% endblock %}
{% block content %}
    <div class="container">
    <div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-6">
        <div class="card card-body my-1">
            <h3 class="text-primary">{% if object %}Update&nbsp;{{ object.fname }}{% else %}New Profile{% endif %}</h3>
            <hr>
            <form method="post" class="form-horizontal" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="form-group">
                    <button type="submit" class="btn btn-outline-info">{% if object %}Update{% else %}Submit{% endif %}</button>
                </div>
            </form>
        </div>
    </div>
    </div>
    </div>
{% endblock %}